### PR TITLE
spelling corrected - Drupa1 to Drupal

### PR DESCRIPTION
**Pull request by DanStevensonMSFT**
fixed an embarrassing spelling error that used a 1 (one) instead of l (ell) for the last character in the name of CMS app Drupal (not Drupa1)

### CODE REVIEW

**Comment by DanStevensonMSFT** [comment]
fixed spelling error for CMS app name Drupal (not Drupa1)

**Comment by Danielabom** [comment]
Hi @DanStevensonMSFT, we use a different repo to create PRs. I created a PR last Friday to correct this issue: https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch-pr/pull/1578. If that's okay, can I close this one?

**Comment by DanStevensonMSFT** [comment]
Yes, of course - I was just clicking the path of least resistance. Will that typo get corrected, then?

________________________________

**Comment by Danielabom** [comment]
Got it. Yes, @DanStevensonMSFT, the typo will be fixed in this PR: https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch-pr/pull/1578. Thanks!

**Pull request closed without merging**
