### PR TITLE
Update custom-filters.md

### PR DESCRIPTION
**Pull request by Revathi-b**
Updated note after Manage custom filters section

### CODE REVIEW

**Comment by jeffkizn** [comment]
@Revathi-b How long do you plan to stay in TR? Generally, if this is a short time we wouldn't make this change.

**Comment by Revathi-b** [comment]
> @Revathi-b How long do you plan to stay in TR? Generally, if this is a short time we wouldn't make this change.

@jeffkizn The Custom filters will be in TR till Jan 2022.

**Comment by jeffkizn** [comment]
@Revathi-b one more question - the admin needs to be in TR to see custom filters option in the admin ui. Does the end user also need to be in TR to see the custom filters in the vertical?

**Comment by maheshsinghania** [comment]
@jeffkizn Both Admin and end user should be in TR. 
Admin side we have restrictions implemented to not allow customization in OOB verticals. SERP side also we are limiting to showing custom filters on custom verticals.

**Comment by HenryatSolu** [comment]
I have configured one custom vertical (content SharePoint, no query rule) with custom filters using OOB managed property (refinable string) and in another tenant modified OOB verticals with custom filters, again refinable strings. I am not seeing the custom filters on vertical pages after 20 hours. Should I wait, get support or have I misunderstood this documentation? Thank you for any information.

I am in Targeted Release for all users in both tenants My understanding of this documentation is that I should be seeing custom filters in both tenants on both custom and OOB vertical pages. I have verified the managed properties used for filtering are populated.

**Comment by maheshsinghania** [comment]
@HenryatSolu 
Custom filters on DateTime and Text properties are in GA. Hence you should be able to configure and view them. Other data types like integers and boolean are not supported yet.

Please try with appending the text &CacheClear=true to your search URL to load the latest settings for the vertical.
If the search results correspond to at least 1 filter value then you should be able to see the filters dropdown. 

Thanks.

**Pull request merged**
