### PR TITLE
Update licensing.md

### PR DESCRIPTION
**Pull request by hhauk**
Changed licensing language to include A5 and academic licensing.

### CODE REVIEW

**Comment by jeffkizn** [comment]
@mecampos please review language and content.

**Comment by Haukeberg-EDU** [comment]
Source for comment: Internal Modern Work FAQ, from page 50
https://transform.microsoft.com/modernwork/download?assetname=assets%2FModern_Work_Licensing_FAQ.docx

**Review by mecampos — CHANGES_REQUESTED** [review]
If the intention of this update is to clarify that the entitlement is not included with an A5 license please note the following:
The A5 license is not mentioned in this article, we are not suggesting that the user can use A5, it is clear that the entitlement is only available with Microsoft 365 E5 or with Office 365 E5.

Please evaluate if this update is required, and if so use the following text:

The Microsoft 365 E5 or Office 365 E5 license type includes entitlement to 500 items of index quota, which counts towards your organization's quota for ingesting content from Graph connectors. Note that this is not included with Microsoft 365 A5 or Office 365 A5.

**Comment by hhauk** [comment]
> If the intention of this update is to clarify that the entitlement is not included with an A5 license please note the following:
> The A5 license is not mentioned in this article, we are not suggesting that the user can use A5, it is clear that the entitlement is only available with Microsoft 365 E5 or with Office 365 E5.
> 
> Please evaluate if this update is required, and if so use the following text:
> 
> The Microsoft 365 E5 or Office 365 E5 license type includes entitlement to 500 items of index quota, which counts towards your organization's quota for ingesting content from Graph connectors. Note that this is not included with Microsoft 365 A5 or Office 365 A5.

This update is essential to the product licensing for Academic users as it deviates significantly (not avaliable) and require a purchase. We must make that clear and the text you suggested does just that. Lets go with your suggested text.

**Review by mecampos — APPROVED** [review]

**Pull request merged**
