### PR TITLE
Proxy authentication is currently not supported.

### PR DESCRIPTION
**Pull request by HolgerLutz**

### CODE REVIEW

**Comment by mecampos** [comment]
@HolgerLutz Could you please provide more details about the reason for this update?
It's not clear what we are trying to communicate with this sentence.

**Comment by HolgerLutz** [comment]
@mecampos Our customers might have proxies in their on-premises environments - if they have a proxy that requires proxy authentication, the connector can't authenticate on the proxy - similar how the AAD-application proxy connector works that is documented here -> https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-configure-connectors-with-proxy-servers#proxy-authentication

**Comment by mecampos** [comment]
@HolgerLutz, Please use the following text to add the comment, consider that it should be formatted as a note:

" > [!NOTE]
> Proxy authentication is not currently supported. If your configuration has a proxy that requires authentication our recommendation is to allow the connector anonymous access to the Internet destinations. "

Also, note that the name of this file changed recently, additional steps might be required to resolve the conflicts on this branch.
New file name: OfficeDocs-MicrosoftSearch/MicrosoftSearch/graph-connector-agent.md

**Comment by jeffkizn** [comment]
I'm making this change on a different PR

**Pull request closed without merging**
