### PR TITLE
Update manage-verticals.md

### PR DESCRIPTION
**Pull request by sarliu**
Adding a video vertical limitation

### CODE REVIEW

**Comment by jypal6** [comment]
@sarliu I dont think this is the right repository. Go to verticals page using the following link - https://review.learn.microsoft.com/en-us/microsoftsearch/manage-verticals and then edit the page to raise the PR. 

Additionally, the current line is verbose, consider editing to "Video vertical is available in Microsoft Search in Bing and will roll out to Microsoft Search in Office and SharePoint soon."

I have added the SharePoint end point as I assume it will also be available. Can you make these changes and raise a different PR.

**Comment by sarliu** [comment]
@jypal6 Thanks for the heads up, Jyoti! After I follow that link and click on the edit button, it shows me a 404 error page for this: https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch-pr/blob/main/MicrosoftSearch/manage-verticals.md

**Comment by jypal6** [comment]
Looks like you do not have access to raise a PR for this. Can you let me know your release dates and I can help you with the edit this time around. For the access, Brian Stucker is driving the documentation work now. perhaps reach out to him

**Comment by sarliu** [comment]
I appreciate your help, Jyoti! We already checked in the ship PR and it should be deployed by the end of the week. I'll reach out to Brian on the access issue.

**Comment by wobba** [comment]
Closing as the video vertical has shipped.

**Pull request closed without merging**
