### PR TITLE
Graph connector quota limit display state changes.

### PR DESCRIPTION
**Pull request by srishashwat**

### CODE REVIEW

**Comment by srishashwat** [comment]
> 

@microsoft-github-policy-service agree company="Microsoft"

**Comment by srishashwat** [comment]
Please merge these changes.

**Review by msharshkum — APPROVED** [review]
Please make it >= 100%

**Comment by srishashwat** [comment]
@msharshkum Review comment related changes committed.

**Review by msharshkum — APPROVED** [review]

**Review by msharshkum — APPROVED** [review]

**Review by msharshkum — APPROVED** [review]

**Review by msharshkum — APPROVED** [review]

**Review by msharshkum — APPROVED** [review]

**Pull request merged**
