### PR TITLE
Updating iframe attributes to include title

### PR DESCRIPTION
**Pull request by kevh-dev**
Including title attribute on iframe so customer will have better accessibility.

### CODE REVIEW

**Comment by dawholl** [comment]
@kevh-dev, @jeffkizn, reviewing the suggested changes to the code samples with the feature owners. May take a day or two to evaluate this suggested change.

**Comment by dawholl** [comment]
@kevh-dev sounds like Soujanya has additional changes to this topic. Would prefer to make all changes at once so reviewers can see delta between live content and updates.

**Comment by Posposoft** [comment]
732751

**Comment by dawholl** [comment]
This and other content updates are now live: https://docs.microsoft.com/en-us/microsoftsearch/add-a-search-box-to-your-intranet-site
@kevh-dev, closing this PR

**Pull request closed without merging**
