### PR TITLE
Update manage-bookmarks.md

### PR DESCRIPTION
**Pull request by ahalyar6**
I am proposing a change to make the limit on number of bookmarks more explicit to customers.

### CODE REVIEW

**Comment by ahalyar6** [comment]
@luizfls would be able to approve my PR please?

**Comment by luizfls** [comment]
@monaray97 @msharshkum @jypal6 -- appreciate your help with this PR.

**Comment by monaray97** [comment]
@luizfls done!

**Comment by ahalyar6** [comment]
Hi @monaray97 , thanks for merging the changes - when would this change appear in public documentation? I am still seeing the original version of the text in the docs online.

new version:
image

original version:
image

**Comment by jypal6** [comment]
Hey @***@***.***> was the change made in review.learn.microsoft.com or in learn.microsoft.com. The changes should be reflected in 24 hours.

Best Regards,
Jyoti Pal
[she/her]
Senior Product Manager
Microsoft Search
[Microsoft Logo]
________________________________

**Comment by jypal6** [comment]
Hey Ahalya,

The change needs to be made on review.learn.microsoft.com. Take the URL of the page you had edited and append "review." to it and edit the document again. I can approve the PR if i have the merging rights to this document as well.

Best Regards,
Jyoti Pal
[she/her]
Senior Product Manager
Microsoft Search
[Microsoft Logo]
________________________________

**Pull request merged**
